"""
Django settings for uuspro project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pk(*s6y35&39=@w#$g@d&7xzc6l(op31z!t3asi15%s+(^dny_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
UDU_IP = '172.31.65.123'
ALLOWED_HOSTS = ['tuts-devel.wfqasiqfhr.us-west-2.elasticbeanstalk.com','tuts-env.wfqasiqfhr.us-west-2.elasticbeanstalk.com', '127.0.0.1', UDU_IP]


# Application definition
INSTALLED_APPS = ['rest_framework',
    'simple_gui.apps.SimpleGuiConfig',
    'uusapp.apps.UusappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'rest_framework.authtoken',]


'''
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )
}
'''

MIDDLEWARE = ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',]

ROOT_URLCONF = 'uuspro.urls'

TEMPLATES = [{
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': ['django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',],
        },
    },]

WSGI_APPLICATION = 'uuspro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
if(sys.platform == "linux"):
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.postgresql_psycopg2',
			'NAME': "ebdb",
			'USER': "administraator",
			'PASSWORD': "Nossuonbeebi92",
			'HOST': "aaghowdt333l1r.cbfuxup0zpv7.us-west-2.rds.amazonaws.com",
			'PORT': 5432,
		}
	}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'uus',
            'USER': 'admin',
            'PASSWORD': 'Nossuonbeebi92',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }	

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [{
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },]

#TODO think about whether we should implement the login system in the app only
#or in the template universally.  Considering that
# In my REST i need a different login system, app based seems to be okay
LOGIN_REDIRECT_URL = '/simplegui/'
LOGIN_URL = '/simplegui/login/'


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = 'static'


# Media files, e.g.  images stguff
MEDIA_ROOT = os.path.join(BASE_DIR,'media') # Lets
MEDIA_URL = '/media/'
