# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_images', to='uusapp.Eventgroup'),
        ),
    ]
