# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uusapp', '0003_auto_20161207_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='group',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_images', to='uusapp.Eventgroup'),
        ),
        migrations.AlterField(
            model_name='img',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
